#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

application=`getApplication`

./../common/printDate begin
runApplication blockMesh
./../common/printDate blockMesh
runApplication setFields
./../common/printDate setFields
runApplication funkySetFields -time 0
./../common/printDate funkySetFields
runApplication decomposePar -cellDist
./../common/printDate decomposePar
runParallel $application
./../common/printDate $application
runApplication reconstructPar
./../common/printDate reconstructPar
runApplication foamToVTK
./../common/printDate foamToVTK

#------------------------------------------------------------------------------
