#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

./printDate begin
runApplication blockMesh
./printDate blockMesh
runApplication setFields
./printDate setFields
runApplication funkySetFields -time 0
./printDate funkySetFields
runApplication decomposePar -cellDist
./printDate decomposePar
runParallel $application
./printDate $application
runApplication reconstructPar
./printDate reconstructPar
runApplication foamToVTK
./printDate foamToVTK

#------------------------------------------------------------------------------
